filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/spring-boot-logger.log
    fields:
      application: spring-boot-app
    fields_under_root: true

metrics:
  enabled: false

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]


output.logstash:
  hosts: ["logstash:5044"]